services:


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum_app
    ports:
      - "8080:8080"
    cpus: ${APP_CPU_LIMIT}
    mem_limit: 512m
    mem_reservation: 256m

    env_file:
      - .env
    environment:

      - SERVER_TOMCAT_MAX_THREADS=${TOMCAT_MAX_THREADS}
      - SERVER_TOMCAT_MIN_SPARE_THREADS=${TOMCAT_MIN_SPARE_THREADS}

      - SPRING_JPA_SHOW_SQL=${SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false


    restart: unless-stopped




