services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: backend
    deploy:
      resources:
        limits:
          cpus: "${LIMITS_CPU}"
          memory: ${LIMITS_MEM}
        reservations:
          cpus: "${RESERV_CPU}"
          memory: ${RESERV_MEM}
    ports:
      - "8080:8080"
    env_file:
      - .env
    enviroment:
      SERVER_TOMCAT_MAX_THREADS: ${LIMITS_THREADS}
      SPRING_JPA_SHOW_SQL: "false"