server.port=8081
crud.service.url=http://museum-app:8080

observability.window.short=10
observability.window.medium=30
observability.window.long=60
observability.schedule.ms=10000


spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration